package com.blueocean.app.assistantmanage.dto;

import java.io.Serializable;
import java.util.Date;

public class DrugOrderDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_order.order_id
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    private String orderId;

  
    private String orderStatus;

  
  
    private String orderType;

   
    private Integer userId;

   
    private String orderPhone;

    private String orderAddr;


   
    private Date orderTime;
    private Date orderCompleteTime;
    private Date closeOrderTime;
    private static final long serialVersionUID = 1L;

    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_id
     *
     * @param orderId the value for drug_order.order_id
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.order_status
     *
     * @return the value of drug_order.order_status
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_status
     *
     * @param orderStatus the value for drug_order.order_status
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.order_type
     *
     * @return the value of drug_order.order_type
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_type
     *
     * @param orderType the value for drug_order.order_type
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.user_id
     *
     * @return the value of drug_order.user_id
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.user_id
     *
     * @param userId the value for drug_order.user_id
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.order_phone
     *
     * @return the value of drug_order.order_phone
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public String getOrderPhone() {
        return orderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_phone
     *
     * @param orderPhone the value for drug_order.order_phone
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderPhone(String orderPhone) {
        this.orderPhone = orderPhone == null ? null : orderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.order_addr
     *
     * @return the value of drug_order.order_addr
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public String getOrderAddr() {
        return orderAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_addr
     *
     * @param orderAddr the value for drug_order.order_addr
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderAddr(String orderAddr) {
        this.orderAddr = orderAddr == null ? null : orderAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.drug_recycle_site_id
     *
     * @return the value of drug_order.drug_recycle_site_id
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
  
   
   
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_time
     *
     * @param orderTime the value for drug_order.order_time
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.order_complete_time
     *
     * @return the value of drug_order.order_complete_time
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public Date getOrderCompleteTime() {
        return orderCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.order_complete_time
     *
     * @param orderCompleteTime the value for drug_order.order_complete_time
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setOrderCompleteTime(Date orderCompleteTime) {
        this.orderCompleteTime = orderCompleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_order.close_order_time
     *
     * @return the value of drug_order.close_order_time
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public Date getCloseOrderTime() {
        return closeOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_order.close_order_time
     *
     * @param closeOrderTime the value for drug_order.close_order_time
     *
     * @mbggenerated Tue Jul 25 16:54:12 CST 2017
     */
    public void setCloseOrderTime(Date closeOrderTime) {
        this.closeOrderTime = closeOrderTime;
    }


}