package com.blueocean.app.customermanage.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.blueocean.app.customermanage.dto.DrugRecycleSiteDo;
import com.blueocean.app.customermanage.entity.PharmacyResponseDTO;
import com.blueocean.app.assistantmanage.web.LoginUser;
import com.blueocean.app.customermanage.entity.SiteInRangeDTO;


@Mapper
public interface DrugRecycleSiteDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	int insert(DrugRecycleSiteDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	int insertSelective(DrugRecycleSiteDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	DrugRecycleSiteDo selectByPrimaryKey(Integer id);
    DrugRecycleSiteDo selectBypassword(LoginUser user);

	List<DrugRecycleSiteDo> selectExistAccount(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	int updateByPrimaryKeySelective(DrugRecycleSiteDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table drug_recycle_site
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	int updateByPrimaryKey(DrugRecycleSiteDo record);

	/**
	 * 
	 * @author wangxinyu
	 * @return
	 * @time 2017年7月12日 下午6:09:06
	 * @params listPharmacyByParams
	 * @todo TODO
	 */
	List<PharmacyResponseDTO> listPharmacyByParams(Map<String, Object> params);

	/**
	 * 
	 * @param record
	 * @return
	 */
	List<SiteInRangeDTO> listPharmacyInRange(Map<String, Object> params);
	/**
	 * 
	 * @param account
	 * @param password
	 * @return
	 */
	DrugRecycleSiteDo selectSiteByConsition(@Param("account") String account, @Param("password") String password);
}