package com.blueocean.app.assistantmanage.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.blueocean.app.assistantmanage.web.DrugOrderWeb;
import com.blueocean.app.assistantmanage.dto.DrugOrderDo;

@Mapper
public interface DrugOrderSelectDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int insert(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int insertSelective(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    DrugOrderDo selectByPrimaryKey(String orderId);
    Integer  selectCountByUserId(DrugOrderWeb drugOrderWeb);
    List<DrugOrderDo> selectAllOrder(DrugOrderWeb drugOrderWeb);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int updateByPrimaryKeySelective(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int updateByPrimaryKey(DrugOrderDo record);
}