package com.blueocean.app.assistantmanage.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.blueocean.app.assistantmanage.dto.UserAccessTokenDo;
@Mapper
public interface UserAccessTokenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    int deleteByPrimaryKey(Long tokenid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    int insert(UserAccessTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    int insertSelective(UserAccessTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    List<UserAccessTokenDo> selectByPUserId(Integer userid);
    UserAccessTokenDo selectByPrimaryKey(Long tokenid);
    UserAccessTokenDo selectBySession(String session);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    int updateByPrimaryKeySelective(UserAccessTokenDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccesstoken
     *
     * @mbggenerated Thu Jul 27 14:12:23 CST 2017
     */
    int updateByPrimaryKey(UserAccessTokenDo record);
    int updateByTime(UserAccessTokenDo record);
}