package com.blueocean.app.customermanage.entity;

import java.io.Serializable;
import java.util.Date;

public class PharmacyResponseDTO implements Serializable {

	private Integer id;

	private String account;

	private String password;

	private String siteName;

	private String siteType;

	private String siteTypeName;

	private String contactName;

	private String contactPhone;

	private String provinceName;

	private String cityName;

	private String fullAddress;
	private String detailAddress;// 详细地址

	private String isActive;

	private String isActiveName;

	private String gmtCreate;

	private Date gmtModified;

	private Integer provinceId;

	private Integer cityId;
	private String cityCode;// 城市编码

	private String lng;// 经度
	private String lat;// 纬度
	private String autoPosition;// 位置信息

	private static final long serialVersionUID = 1L;

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.id
	 *
	 * @param id
	 *            the value for drug_recycle_site.id
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.account
	 *
	 * @return the value of drug_recycle_site.account
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.account
	 *
	 * @param account
	 *            the value for drug_recycle_site.account
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.password
	 *
	 * @return the value of drug_recycle_site.password
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.password
	 *
	 * @param password
	 *            the value for drug_recycle_site.password
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.site_name
	 *
	 * @return the value of drug_recycle_site.site_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.site_name
	 *
	 * @param siteName
	 *            the value for drug_recycle_site.site_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName == null ? null : siteName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.site_type
	 *
	 * @return the value of drug_recycle_site.site_type
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getSiteType() {
		return siteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.site_type
	 *
	 * @param siteType
	 *            the value for drug_recycle_site.site_type
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setSiteType(String siteType) {
		this.siteType = siteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.contact_name
	 *
	 * @return the value of drug_recycle_site.contact_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.contact_name
	 *
	 * @param contactName
	 *            the value for drug_recycle_site.contact_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName == null ? null : contactName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.contact_phone
	 *
	 * @return the value of drug_recycle_site.contact_phone
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.contact_phone
	 *
	 * @param contactPhone
	 *            the value for drug_recycle_site.contact_phone
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone == null ? null : contactPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.province_name
	 *
	 * @return the value of drug_recycle_site.province_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.province_name
	 *
	 * @param provinceName
	 *            the value for drug_recycle_site.province_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName == null ? null : provinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.city_name
	 *
	 * @return the value of drug_recycle_site.city_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.city_name
	 *
	 * @param cityName
	 *            the value for drug_recycle_site.city_name
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.full_address
	 *
	 * @return the value of drug_recycle_site.full_address
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getFullAddress() {
		return fullAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.full_address
	 *
	 * @param fullAddress
	 *            the value for drug_recycle_site.full_address
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress == null ? null : fullAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.is_active
	 *
	 * @return the value of drug_recycle_site.is_active
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public String getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.is_active
	 *
	 * @param isActive
	 *            the value for drug_recycle_site.is_active
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setIsActive(String isActive) {
		this.isActive = isActive == null ? null : isActive.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.gmt_modified
	 *
	 * @return the value of drug_recycle_site.gmt_modified
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for drug_recycle_site.gmt_modified
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.province_id
	 *
	 * @return the value of drug_recycle_site.province_id
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public Integer getProvinceId() {
		return provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.province_id
	 *
	 * @param provinceId
	 *            the value for drug_recycle_site.province_id
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column drug_recycle_site.city_id
	 *
	 * @return the value of drug_recycle_site.city_id
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column drug_recycle_site.city_id
	 *
	 * @param cityId
	 *            the value for drug_recycle_site.city_id
	 *
	 * @mbggenerated Wed Jul 12 16:43:48 CST 2017
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getGmtCreate() {
		return gmtCreate;
	}

	public void setGmtCreate(String gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	public String getSiteTypeName() {
		if (this.siteType == "1") {
			siteTypeName = "药店";
		} else {
			siteTypeName = "药房";
		}
		return siteTypeName;
	}

	public void setSiteTypeName(String siteTypeName) {
		this.siteTypeName = siteTypeName;
	}

	public String getIsActiveName() {
		if ("1".equals(this.isActive)) {
			isActiveName = "开通中";
		} else {
			isActiveName = "未开通";
		}
		return isActiveName;
	}

	public void setIsActiveName(String isActiveName) {
		this.isActiveName = isActiveName;
	}

	public String getLng() {
		return lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getDetailAddress() {
		return detailAddress;
	}

	public void setDetailAddress(String detailAddress) {
		this.detailAddress = detailAddress;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getAutoPosition() {
		return autoPosition;
	}

	public void setAutoPosition(String autoPosition) {
		this.autoPosition = autoPosition;
	}

}
